-- =====================================================================
-- NWM-138: Snowflake environments for the Oracle migration
-- Creates DEV and PROD, each with BRONZE / SILVER / GOLD layers,
-- plus the roles and warehouses that use them.
--
-- Run ONCE, top to bottom, in a Snowsight worksheet.
-- (In a real company, the Snowflake admin (Tom) runs this, not you.)
-- =====================================================================

-- ---------- 1. Roles (USERADMIN creates roles) ----------
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS NW_DEV_ENGINEER  COMMENT = 'Engineers: full control of NORTHWIND_DEV';
CREATE ROLE IF NOT EXISTS NW_PROD_DEPLOYER COMMENT = 'CI/CD only: owns NORTHWIND_PROD objects';
CREATE ROLE IF NOT EXISTS NW_ANALYST       COMMENT = 'Analysts: read-only on PROD GOLD';

-- ---------- 2. Role hierarchy + give yourself the roles (SECURITYADMIN) ----------
USE ROLE SECURITYADMIN;

GRANT ROLE NW_DEV_ENGINEER  TO ROLE SYSADMIN;
GRANT ROLE NW_PROD_DEPLOYER TO ROLE SYSADMIN;
GRANT ROLE NW_ANALYST       TO ROLE SYSADMIN;

SET me = CURRENT_USER();
GRANT ROLE NW_DEV_ENGINEER  TO USER IDENTIFIER($me);
GRANT ROLE NW_ANALYST       TO USER IDENTIFIER($me);
-- Practice-only: in a real company you would NOT have the PROD deployer role.
-- Only the GitHub Actions service user gets it (we set that up in Phase 8).
GRANT ROLE NW_PROD_DEPLOYER TO USER IDENTIFIER($me);

-- ---------- 3. Warehouses, databases, schemas (SYSADMIN) ----------
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS NW_DEV_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Development work';
CREATE WAREHOUSE IF NOT EXISTS NW_PROD_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Production loads, tasks and analyst queries';

-- One database per ENVIRONMENT, one schema per LAYER
CREATE DATABASE IF NOT EXISTS NORTHWIND_DEV  COMMENT = 'DEV: experiment freely';
CREATE SCHEMA   IF NOT EXISTS NORTHWIND_DEV.BRONZE COMMENT = 'Exact copy of Oracle';
CREATE SCHEMA   IF NOT EXISTS NORTHWIND_DEV.SILVER COMMENT = 'Cleaned per mapping rules';
CREATE SCHEMA   IF NOT EXISTS NORTHWIND_DEV.GOLD   COMMENT = 'Business outputs';

CREATE DATABASE IF NOT EXISTS NORTHWIND_PROD COMMENT = 'PROD: changed only through CI/CD';
CREATE SCHEMA   IF NOT EXISTS NORTHWIND_PROD.BRONZE COMMENT = 'Exact copy of Oracle';
CREATE SCHEMA   IF NOT EXISTS NORTHWIND_PROD.SILVER COMMENT = 'Cleaned per mapping rules';
CREATE SCHEMA   IF NOT EXISTS NORTHWIND_PROD.GOLD   COMMENT = 'Business outputs';

-- Hand DEV to the engineers, PROD to the deployer.
-- Because both roles roll up to SYSADMIN, SYSADMIN can still see everything.
GRANT OWNERSHIP ON DATABASE NORTHWIND_DEV        TO ROLE NW_DEV_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   NORTHWIND_DEV.BRONZE TO ROLE NW_DEV_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   NORTHWIND_DEV.SILVER TO ROLE NW_DEV_ENGINEER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   NORTHWIND_DEV.GOLD   TO ROLE NW_DEV_ENGINEER COPY CURRENT GRANTS;

GRANT OWNERSHIP ON DATABASE NORTHWIND_PROD        TO ROLE NW_PROD_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   NORTHWIND_PROD.BRONZE TO ROLE NW_PROD_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   NORTHWIND_PROD.SILVER TO ROLE NW_PROD_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   NORTHWIND_PROD.GOLD   TO ROLE NW_PROD_DEPLOYER COPY CURRENT GRANTS;

-- ---------- 4. Warehouse + analyst access (SECURITYADMIN) ----------
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE NW_DEV_WH  TO ROLE NW_DEV_ENGINEER;
GRANT USAGE ON WAREHOUSE NW_PROD_WH TO ROLE NW_PROD_DEPLOYER;
GRANT USAGE ON WAREHOUSE NW_PROD_WH TO ROLE NW_ANALYST;

-- Analysts see ONLY the GOLD layer of PROD (never Bronze/Silver, never DEV)
GRANT USAGE ON DATABASE NORTHWIND_PROD      TO ROLE NW_ANALYST;
GRANT USAGE ON SCHEMA   NORTHWIND_PROD.GOLD TO ROLE NW_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NORTHWIND_PROD.GOLD TO ROLE NW_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA NORTHWIND_PROD.GOLD TO ROLE NW_ANALYST;

-- ---------- 5. Budget guard (ACCOUNTADMIN only) ----------
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS NW_RM
  WITH CREDIT_QUOTA = 30 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75  PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND
           ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE NW_DEV_WH  SET RESOURCE_MONITOR = NW_RM;
ALTER WAREHOUSE NW_PROD_WH SET RESOURCE_MONITOR = NW_RM;

-- ---------- 6. Verify (acceptance criteria of NWM-138) ----------
SHOW DATABASES LIKE 'NORTHWIND%';            -- expect 2, owners NW_DEV_ENGINEER / NW_PROD_DEPLOYER
SHOW SCHEMAS IN DATABASE NORTHWIND_DEV;      -- expect BRONZE, SILVER, GOLD (+ INFORMATION_SCHEMA, PUBLIC)
SHOW SCHEMAS IN DATABASE NORTHWIND_PROD;

-- Test 1: engineers can build in DEV
USE ROLE NW_DEV_ENGINEER;
USE WAREHOUSE NW_DEV_WH;
CREATE TABLE NORTHWIND_DEV.BRONZE.SMOKE_TEST (id INT);   -- should succeed
DROP TABLE NORTHWIND_DEV.BRONZE.SMOKE_TEST;

-- Test 2: engineers CANNOT touch PROD
CREATE TABLE NORTHWIND_PROD.BRONZE.SMOKE_TEST (id INT);  -- EXPECTED ERROR: insufficient privileges / does not exist
