-- =====================================================================
-- PROJECT 3 - PHASE 0 - Script 01: build Northwind's legacy back-office system
-- Run as NORTHWIND, connected to FREEPDB1. Safe to re-run (it drops and rebuilds).
--
-- Contains, on purpose, the habits of a real 15-year-old Oracle system:
--   * DATE columns that secretly hold a time of day
--   * NUMBER columns with no precision (order_total, discount)
--   * Sequences + triggers for IDs (pre-12c style) and "last_updated" stamping
--   * Y/N CHAR(1) flags instead of booleans
--   * '' (empty string) silently stored as NULL
--   * A CLOB column with commas, quotes and line breaks
--   * Placeholder dates (1900-01-01), accented names, apostrophes
--   * PL/SQL business logic + a DBMS_SCHEDULER nightly job
-- =====================================================================
SET DEFINE OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SET FEEDBACK ON

PROMPT ===== 1. Cleaning up any previous run =====
BEGIN
  BEGIN
    DBMS_SCHEDULER.DROP_JOB(job_name => 'NIGHTLY_BATCH', force => TRUE);
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN ('ORDER_LINES','ORDERS','PRODUCTS','EMPLOYEES','CUSTOMERS',
                                 'BATCH_LOG','MONTHLY_SALES_SUMMARY')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
  FOR s IN (SELECT sequence_name FROM user_sequences
            WHERE sequence_name IN ('CUSTOMERS_SEQ','EMPLOYEES_SEQ','PRODUCTS_SEQ','ORDERS_SEQ')) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
  FOR o IN (SELECT object_name, object_type FROM user_objects
            WHERE object_type IN ('PROCEDURE','VIEW')
              AND object_name IN ('CALC_LOYALTY_TIERS','REFRESH_SALES_SUMMARY','V_CUSTOMER_ORDERS')) LOOP
    EXECUTE IMMEDIATE 'DROP ' || o.object_type || ' ' || o.object_name;
  END LOOP;
END;
/

WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT ===== 2. Sequences (legacy auto-numbering) =====
CREATE SEQUENCE customers_seq START WITH 1001 NOCACHE;
CREATE SEQUENCE employees_seq START WITH 1 NOCACHE;
CREATE SEQUENCE products_seq  START WITH 1 NOCACHE;
CREATE SEQUENCE orders_seq    START WITH 500001 NOCACHE;

PROMPT ===== 3. Tables =====
CREATE TABLE customers (
  customer_id    NUMBER(10)        CONSTRAINT customers_pk PRIMARY KEY,
  first_name     VARCHAR2(50 CHAR) NOT NULL,
  last_name      VARCHAR2(50 CHAR) NOT NULL,
  email          VARCHAR2(120),
  phone          VARCHAR2(30),
  city           VARCHAR2(60),
  state          CHAR(2),
  customer_type  VARCHAR2(10) DEFAULT 'RETAIL'
                 CONSTRAINT customers_type_ck CHECK (customer_type IN ('RETAIL','WHOLESALE')),
  loyalty_tier   VARCHAR2(10),
  is_active      CHAR(1) DEFAULT 'Y'
                 CONSTRAINT customers_active_ck CHECK (is_active IN ('Y','N')),
  created_date   DATE,
  last_updated   DATE
);

CREATE TABLE employees (
  employee_id     NUMBER(6)         CONSTRAINT employees_pk PRIMARY KEY,
  first_name      VARCHAR2(50 CHAR) NOT NULL,
  last_name       VARCHAR2(50 CHAR) NOT NULL,
  email           VARCHAR2(120)     NOT NULL,
  job_title       VARCHAR2(50),
  national_id     VARCHAR2(11),
  hire_date       DATE,
  salary          NUMBER(10,2),
  commission_pct  NUMBER(4,2),
  manager_id      NUMBER(6) CONSTRAINT employees_mgr_fk REFERENCES employees (employee_id),
  last_updated    DATE
);

CREATE TABLE products (
  product_id    NUMBER(6)          CONSTRAINT products_pk PRIMARY KEY,
  product_name  VARCHAR2(100 CHAR) NOT NULL,
  category      VARCHAR2(30),
  unit_price    NUMBER(10,2),
  discontinued  CHAR(1) DEFAULT 'N'
                CONSTRAINT products_disc_ck CHECK (discontinued IN ('Y','N')),
  last_updated  DATE
);

CREATE TABLE orders (
  order_id      NUMBER(10)   CONSTRAINT orders_pk PRIMARY KEY,
  customer_id   NUMBER(10)   NOT NULL CONSTRAINT orders_cust_fk REFERENCES customers (customer_id),
  employee_id   NUMBER(6)    CONSTRAINT orders_emp_fk REFERENCES employees (employee_id),
  order_date    DATE         NOT NULL,
  status        VARCHAR2(20) NOT NULL,
  ship_city     VARCHAR2(60),
  notes         CLOB,
  order_total   NUMBER,
  last_updated  DATE
);

CREATE TABLE order_lines (
  order_id      NUMBER(10) CONSTRAINT ol_order_fk REFERENCES orders (order_id),
  line_no       NUMBER(3),
  product_id    NUMBER(6)  NOT NULL CONSTRAINT ol_product_fk REFERENCES products (product_id),
  quantity      NUMBER(5)  NOT NULL,
  unit_price    NUMBER(10,2) NOT NULL,
  discount      NUMBER,
  last_updated  DATE,
  CONSTRAINT order_lines_pk PRIMARY KEY (order_id, line_no)
);

-- Added in 2016 by a newer developer, so it uses a 12c identity column instead of a sequence
CREATE TABLE batch_log (
  log_id         NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT batch_log_pk PRIMARY KEY,
  job_name       VARCHAR2(60),
  started_at     DATE,
  finished_at    DATE,
  rows_affected  NUMBER,
  status         VARCHAR2(10),
  error_message  VARCHAR2(4000)
);

CREATE TABLE monthly_sales_summary (
  sales_month    DATE,
  customer_type  VARCHAR2(10),
  order_count    NUMBER,
  gross_revenue  NUMBER,
  refreshed_at   DATE,
  CONSTRAINT mss_pk PRIMARY KEY (sales_month, customer_type)
);

-- The index a watermark-based CDC process will rely on later
CREATE INDEX orders_last_updated_ix    ON orders (last_updated);
CREATE INDEX customers_last_updated_ix ON customers (last_updated);
CREATE INDEX orders_customer_ix        ON orders (customer_id);

PROMPT ===== 4. Triggers (ID assignment + last_updated stamping) =====
CREATE OR REPLACE TRIGGER customers_biu
  BEFORE INSERT OR UPDATE ON customers
  FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.customer_id IS NULL THEN
    :NEW.customer_id := customers_seq.NEXTVAL;
  END IF;
  IF UPDATING OR :NEW.last_updated IS NULL THEN
    :NEW.last_updated := SYSDATE;
  END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER employees_biu
  BEFORE INSERT OR UPDATE ON employees
  FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.employee_id IS NULL THEN
    :NEW.employee_id := employees_seq.NEXTVAL;
  END IF;
  IF UPDATING OR :NEW.last_updated IS NULL THEN
    :NEW.last_updated := SYSDATE;
  END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER products_biu
  BEFORE INSERT OR UPDATE ON products
  FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.product_id IS NULL THEN
    :NEW.product_id := products_seq.NEXTVAL;
  END IF;
  IF UPDATING OR :NEW.last_updated IS NULL THEN
    :NEW.last_updated := SYSDATE;
  END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER orders_biu
  BEFORE INSERT OR UPDATE ON orders
  FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.order_id IS NULL THEN
    :NEW.order_id := orders_seq.NEXTVAL;
  END IF;
  IF UPDATING OR :NEW.last_updated IS NULL THEN
    :NEW.last_updated := SYSDATE;
  END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE TRIGGER order_lines_biu
  BEFORE INSERT OR UPDATE ON order_lines
  FOR EACH ROW
BEGIN
  IF UPDATING OR :NEW.last_updated IS NULL THEN
    :NEW.last_updated := SYSDATE;
  END IF;
END;
/
SHOW ERRORS

PROMPT ===== 5. Generating 15 years of business data (about 1 minute) =====
DECLARE
  TYPE t_str IS TABLE OF VARCHAR2(60 CHAR);
  v_first  t_str;
  v_last   t_str;
  v_city   t_str := t_str('New York','Boston','Chicago','San Antonio','Atlanta','Seattle','Los Angeles','Denver');
  v_state  t_str := t_str('NY','MA','IL','TX','GA','WA','CA','CO');
  v_cat    t_str := t_str('Apparel','Footwear','Home','Electronics','Outdoors');
  v_adj    t_str := t_str('Classic','Premium','Eco');
  v_noun   t_str := t_str('Tee','Hoodie','Denim Jacket','Chino Pants','Rain Coat',
                          'Running Shoe','Leather Boot','Canvas Sneaker','Sandal','Hiking Boot',
                          'Ceramic Mug','Throw Blanket','Desk Lamp','Scented Candle','Wall Clock',
                          'Wireless Earbuds','Phone Charger','Bluetooth Speaker','Smart Watch','USB Hub',
                          'Water Bottle','Daypack','Camping Chair','Headlamp','Trekking Poles');
  TYPE t_num_map IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  v_price_by_id  t_num_map;
  TYPE t_line  IS RECORD (prod NUMBER, qty NUMBER, price NUMBER, disc NUMBER);
  TYPE t_lines IS TABLE OF t_line INDEX BY PLS_INTEGER;
  v_lines_tab  t_lines;
  v_u1 VARCHAR2(20 CHAR); v_u2 VARCHAR2(20 CHAR); v_u3 VARCHAR2(20 CHAR); v_u4 VARCHAR2(20 CHAR);
  v_fn          VARCHAR2(50 CHAR);
  v_ln          VARCHAR2(50 CHAR);
  v_ci          PLS_INTEGER;
  n             PLS_INTEGER;
  v_created     DATE;
  v_order_date  DATE;
  v_oid         NUMBER;
  v_cust        NUMBER;
  v_emp         NUMBER;
  v_nlines      PLS_INTEGER;
  v_total       NUMBER;
  v_rnd         NUMBER;
  v_status      VARCHAR2(20);
  v_notes       VARCHAR2(32767);
  v_ship_city   VARCHAR2(60);
BEGIN
  DBMS_RANDOM.SEED(42);   -- same "random" data every time you run this

  -- Accented names built from Unicode code points, so this file stays plain ASCII
  SELECT UNISTR('Jos\00E9'), UNISTR('Zo\00EB'), UNISTR('M\00FCller'), UNISTR('Nguy\1EC5n')
    INTO v_u1, v_u2, v_u3, v_u4
    FROM dual;
  v_first := t_str('James','Maria','Wei','Aisha',v_u1,v_u2,'Liam','Olivia','Noah','Emma',
                   'Raj','Priya','Chen','Fatima','Lucas','Sofia','Mateo','Hannah','Omar','Yuki');
  v_last  := t_str('Smith','Garcia','O''Brien',v_u3,v_u4,'Patel','Kim','Johnson','Brown','Rossi',
                   'Kowalski','Dubois','Tanaka','Silva','Anderson','Lee','Martin','Clark','Lopez','Wright');

  -- ---------- Employees (25): 1 CEO, 3 managers, 21 sales reps ----------
  FOR i IN 1 .. 25 LOOP
    v_fn := v_first(TRUNC(DBMS_RANDOM.VALUE(1, v_first.COUNT + 1)));
    v_ln := v_last(TRUNC(DBMS_RANDOM.VALUE(1, v_last.COUNT + 1)));
    INSERT INTO employees (first_name, last_name, email, job_title, national_id,
                           hire_date, salary, commission_pct, manager_id, last_updated)
    VALUES (v_fn, v_ln,
            LOWER(SUBSTR(v_fn, 1, 1) || REPLACE(v_ln, '''', '')) || i || '@northwind.example',
            CASE WHEN i = 1 THEN 'CEO' WHEN i <= 4 THEN 'Sales Manager' ELSE 'Sales Rep' END,
            LPAD(TRUNC(DBMS_RANDOM.VALUE(100, 1000)), 3, '0') || '-' ||
            LPAD(TRUNC(DBMS_RANDOM.VALUE(10, 100)), 2, '0')   || '-' ||
            LPAD(TRUNC(DBMS_RANDOM.VALUE(0, 10000)), 4, '0'),
            DATE '2009-01-01' + TRUNC(DBMS_RANDOM.VALUE(0, 5000)),
            CASE WHEN i = 1 THEN 245000
                 WHEN i <= 4 THEN ROUND(DBMS_RANDOM.VALUE(110000, 150000), 2)
                 ELSE ROUND(DBMS_RANDOM.VALUE(48000, 90000), 2) END,
            CASE WHEN i > 4 THEN ROUND(DBMS_RANDOM.VALUE(0.02, 0.12), 2) END,
            CASE WHEN i = 1 THEN NULL WHEN i <= 4 THEN 1 ELSE 2 + MOD(i, 3) END,
            DATE '2024-01-01' + DBMS_RANDOM.VALUE(0, 300));
  END LOOP;

  -- ---------- Products (60) ----------
  FOR i IN 1 .. 60 LOOP
    n := MOD(i - 1, 25) + 1;
    INSERT INTO products (product_name, category, unit_price, discontinued, last_updated)
    VALUES (v_adj(TRUNC((i - 1) / 25) + 1) || ' ' || v_noun(n),
            v_cat(TRUNC((n - 1) / 5) + 1),
            ROUND(DBMS_RANDOM.VALUE(5, 300), 2),
            CASE WHEN DBMS_RANDOM.VALUE < 0.08 THEN 'Y' ELSE 'N' END,
            DATE '2023-06-01' + DBMS_RANDOM.VALUE(0, 400));
  END LOOP;
  FOR r IN (SELECT product_id, unit_price FROM products) LOOP
    v_price_by_id(r.product_id) := r.unit_price;
  END LOOP;

  -- ---------- Customers (2,000) ----------
  FOR i IN 1 .. 2000 LOOP
    v_ci := TRUNC(DBMS_RANDOM.VALUE(1, v_city.COUNT + 1));
    v_fn := v_first(TRUNC(DBMS_RANDOM.VALUE(1, v_first.COUNT + 1)));
    v_ln := v_last(TRUNC(DBMS_RANDOM.VALUE(1, v_last.COUNT + 1)));
    IF MOD(i, 400) = 0 THEN
      v_created := DATE '1900-01-01';     -- legacy "unknown date" placeholder
    ELSE
      v_created := DATE '2012-01-01' + DBMS_RANDOM.VALUE(0, SYSDATE - DATE '2012-01-01');
    END IF;
    INSERT INTO customers (first_name, last_name, email, phone, city, state,
                           customer_type, is_active, created_date, last_updated)
    VALUES (v_fn, v_ln,
            CASE WHEN MOD(i, 50) = 0 THEN NULL
                 ELSE LOWER(REPLACE(v_fn || '.' || v_ln, '''', '')) || i || '@example.com' END,
            CASE WHEN MOD(i, 10) = 0 THEN ''    -- Oracle stores '' as NULL
                 ELSE '555-' || LPAD(TRUNC(DBMS_RANDOM.VALUE(0, 10000)), 4, '0') END,
            v_city(v_ci), v_state(v_ci),
            CASE WHEN DBMS_RANDOM.VALUE < 0.15 THEN 'WHOLESALE' ELSE 'RETAIL' END,
            CASE WHEN DBMS_RANDOM.VALUE < 0.05 THEN 'N' ELSE 'Y' END,
            v_created,
            LEAST(SYSDATE, GREATEST(v_created, DATE '2012-01-01') + DBMS_RANDOM.VALUE(0, 400)));
  END LOOP;
  COMMIT;

  -- ---------- Orders (20,000) + order lines (~50,000) ----------
  FOR i IN 1 .. 20000 LOOP
    v_oid        := orders_seq.NEXTVAL;
    v_order_date := DATE '2019-01-01' + DBMS_RANDOM.VALUE(0, (SYSDATE - 1) - DATE '2019-01-01');
    v_cust       := TRUNC(DBMS_RANDOM.VALUE(1001, 3001));
    v_emp        := TRUNC(DBMS_RANDOM.VALUE(5, 26));
    v_nlines     := TRUNC(DBMS_RANDOM.VALUE(1, 5));
    v_total      := 0;
    v_lines_tab.DELETE;

    FOR l IN 1 .. v_nlines LOOP
      v_lines_tab(l).prod  := TRUNC(DBMS_RANDOM.VALUE(1, 61));
      v_lines_tab(l).qty   := TRUNC(DBMS_RANDOM.VALUE(1, 6));
      v_lines_tab(l).price := v_price_by_id(v_lines_tab(l).prod);
      IF DBMS_RANDOM.VALUE < 0.3 THEN
        v_lines_tab(l).disc := ROUND(DBMS_RANDOM.VALUE(0.05, 0.25), 3);
      ELSE
        v_lines_tab(l).disc := 0;
      END IF;
      -- unrounded on purpose: order_total ends up with up to 5 decimal places
      v_total := v_total + v_lines_tab(l).qty * v_lines_tab(l).price * (1 - v_lines_tab(l).disc);
    END LOOP;

    v_rnd := DBMS_RANDOM.VALUE;
    IF    v_order_date > SYSDATE - 3  THEN v_status := 'PROCESSING';
    ELSIF v_order_date > SYSDATE - 10 THEN v_status := 'SHIPPED';
    ELSIF v_rnd < 0.05                THEN v_status := 'CANCELLED';
    ELSIF v_rnd < 0.09                THEN v_status := 'RETURNED';
    ELSE                                   v_status := 'DELIVERED';
    END IF;

    v_notes := NULL;
    IF MOD(i, 25) = 0 THEN
      v_notes := 'Customer asked for gift wrap, "fragile" items.' || CHR(10) ||
                 'Deliver after 5pm, ring twice.';
    ELSIF MOD(i, 997) = 0 THEN
      v_notes := RPAD('Legacy note carried over from the 2009 system. ', 6000,
                      'Legacy note carried over from the 2009 system. ');
    END IF;

    SELECT city INTO v_ship_city FROM customers WHERE customer_id = v_cust;
    IF DBMS_RANDOM.VALUE < 0.1 THEN
      v_ship_city := v_city(TRUNC(DBMS_RANDOM.VALUE(1, v_city.COUNT + 1)));
    END IF;

    INSERT INTO orders (order_id, customer_id, employee_id, order_date, status,
                        ship_city, notes, order_total, last_updated)
    VALUES (v_oid, v_cust, v_emp, v_order_date, v_status,
            v_ship_city, v_notes, v_total,
            LEAST(SYSDATE, v_order_date + DBMS_RANDOM.VALUE(0, 20)));

    FOR l IN 1 .. v_nlines LOOP
      INSERT INTO order_lines (order_id, line_no, product_id, quantity, unit_price, discount, last_updated)
      VALUES (v_oid, l, v_lines_tab(l).prod, v_lines_tab(l).qty,
              v_lines_tab(l).price, v_lines_tab(l).disc, v_order_date);
    END LOOP;

    IF MOD(i, 5000) = 0 THEN
      COMMIT;
      DBMS_OUTPUT.PUT_LINE('  ... ' || i || ' orders generated');
    END IF;
  END LOOP;
  COMMIT;
END;
/

PROMPT ===== 6. Business logic: loyalty tiers (PL/SQL) =====
CREATE OR REPLACE PROCEDURE calc_loyalty_tiers AS
  -- Rule (from the 2011 marketing spec): spend in the last 12 months,
  -- excluding cancelled and returned orders, decides the tier.
  v_start  DATE := SYSDATE;
  v_rows   NUMBER;
  v_err    VARCHAR2(4000);
BEGIN
  MERGE INTO customers c
  USING (
    SELECT cu.customer_id,
           CASE
             WHEN NVL(SUM(o.order_total), 0) >= 5000 THEN 'PLATINUM'
             WHEN NVL(SUM(o.order_total), 0) >= 2500 THEN 'GOLD'
             WHEN NVL(SUM(o.order_total), 0) >= 1000 THEN 'SILVER'
             ELSE 'BRONZE'
           END AS new_tier
    FROM customers cu
    LEFT JOIN orders o
           ON o.customer_id = cu.customer_id
          AND o.status NOT IN ('CANCELLED', 'RETURNED')
          AND o.order_date >= ADD_MONTHS(TRUNC(SYSDATE), -12)
    GROUP BY cu.customer_id
  ) s
  ON (c.customer_id = s.customer_id)
  WHEN MATCHED THEN
    UPDATE SET c.loyalty_tier = s.new_tier
    WHERE DECODE(c.loyalty_tier, s.new_tier, 0, 1) = 1;   -- NULL-safe "has it changed?"
  v_rows := SQL%ROWCOUNT;

  INSERT INTO batch_log (job_name, started_at, finished_at, rows_affected, status)
  VALUES ('CALC_LOYALTY_TIERS', v_start, SYSDATE, v_rows, 'SUCCESS');
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    v_err := SUBSTR(SQLERRM, 1, 4000);
    ROLLBACK;
    INSERT INTO batch_log (job_name, started_at, finished_at, rows_affected, status, error_message)
    VALUES ('CALC_LOYALTY_TIERS', v_start, SYSDATE, 0, 'FAILED', v_err);
    COMMIT;
    RAISE;
END calc_loyalty_tiers;
/
SHOW ERRORS

PROMPT ===== 7. Business logic: monthly sales summary (PL/SQL) =====
CREATE OR REPLACE PROCEDURE refresh_sales_summary AS
  v_start  DATE := SYSDATE;
  v_rows   NUMBER;
  v_err    VARCHAR2(4000);
BEGIN
  DELETE FROM monthly_sales_summary;
  INSERT INTO monthly_sales_summary (sales_month, customer_type, order_count, gross_revenue, refreshed_at)
  SELECT TRUNC(o.order_date, 'MM'),
         c.customer_type,
         COUNT(*),
         SUM(o.order_total),
         SYSDATE
  FROM orders o
  JOIN customers c ON c.customer_id = o.customer_id
  WHERE o.status NOT IN ('CANCELLED', 'RETURNED')
  GROUP BY TRUNC(o.order_date, 'MM'), c.customer_type;
  v_rows := SQL%ROWCOUNT;

  INSERT INTO batch_log (job_name, started_at, finished_at, rows_affected, status)
  VALUES ('REFRESH_SALES_SUMMARY', v_start, SYSDATE, v_rows, 'SUCCESS');
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    v_err := SUBSTR(SQLERRM, 1, 4000);
    ROLLBACK;
    INSERT INTO batch_log (job_name, started_at, finished_at, rows_affected, status, error_message)
    VALUES ('REFRESH_SALES_SUMMARY', v_start, SYSDATE, 0, 'FAILED', v_err);
    COMMIT;
    RAISE;
END refresh_sales_summary;
/
SHOW ERRORS

PROMPT ===== 8. A reporting view the analysts use =====
CREATE OR REPLACE VIEW v_customer_orders AS
SELECT c.customer_id,
       c.first_name || ' ' || c.last_name  AS customer_name,
       c.customer_type,
       c.loyalty_tier,
       COUNT(o.order_id)                   AS order_count,
       NVL(SUM(o.order_total), 0)          AS lifetime_value,
       MAX(o.order_date)                   AS last_order_date
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.customer_type, c.loyalty_tier;

PROMPT ===== 9. The nightly batch job (runs every day at 02:00) =====
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    job_name        => 'NIGHTLY_BATCH',
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN calc_loyalty_tiers; refresh_sales_summary; END;',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=DAILY;BYHOUR=2;BYMINUTE=0;BYSECOND=0',
    enabled         => TRUE,
    comments        => 'Legacy nightly batch: loyalty tiers + monthly sales summary');
END;
/

PROMPT ===== 10. Run the batch once now, and gather optimizer statistics =====
EXEC calc_loyalty_tiers
EXEC refresh_sales_summary
EXEC DBMS_STATS.GATHER_SCHEMA_STATS(USER)

PROMPT ===== 11. Result: row counts =====
SET PAGESIZE 50
COLUMN table_name FORMAT A25
SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count FROM customers
UNION ALL SELECT 'EMPLOYEES', COUNT(*) FROM employees
UNION ALL SELECT 'PRODUCTS', COUNT(*) FROM products
UNION ALL SELECT 'ORDERS', COUNT(*) FROM orders
UNION ALL SELECT 'ORDER_LINES', COUNT(*) FROM order_lines
UNION ALL SELECT 'MONTHLY_SALES_SUMMARY', COUNT(*) FROM monthly_sales_summary
UNION ALL SELECT 'BATCH_LOG', COUNT(*) FROM batch_log;

PROMPT
PROMPT ===== Legacy system is ready. Welcome to 2009. =====
EXIT
